### ISSUE TITLE
Write Paper

### ISSUE THREAD

**Issue by tholoien** [tholoien/XDGMM#26]
This is an epic to track the progress on the paper writeup for this class and the EmpiriciSN class.
- [x] Create project on Overleaf
- [x] Link Overleaf project to this repo (if possible?)
- [x] Write introduction -- Describe what XDGMM is and how it is used, go over the motivation for creating this class and EmpiriciSN
- [x] Write XDGMM section. 
  - [x] Describe the two fitting methods
  - [x] Go over scikit-learn methods that have been implemented
  - [x] Cover math behind conditioning the model and how it is used
- [x] Write EmpiriciSN section
  - [x] Describe motivation behind this tool
  - [x] Describe the catalogs used to build the base model
  - [x] Demo the results
- [x] Write discussion/summary section
- [x] Submit to arXiv and Astronomy & Computing

**Comment by tholoien** [comment]
Paper is done and submitted to A&A and astroph! (Forgot to update this issue.)
