### ISSUE TITLE
Master Plan

### ISSUE THREAD

**Issue by tholoien** [tholoien/XDGMM#5]
This is a basic roadmap for the tasks that need to be completed. It will be updated to link to sub-issues and to mark progress.
- [x] Add astroML fitting and sampling to the class (#1)
- [x] Add Bovy et al. fitting to the class (#2)
- [x] Build ability to condition the model (#3)
- [x] Add and test methods needed for scikit-learn cross validation (#4)

**Comment by tholoien** [comment]
All necessary functionality has been implemented. Leaving this open for now until the testing and demo notebooks have been finished.

**Comment by tholoien** [comment]
Closing this since the code is working now.
